on:
  - push
  - delete


jobs:

  pass-secret-to-action:
    runs-on: ubuntu-latest
    steps:
      - name: PHP Compatibility
        uses: pantheon-systems/phpcompatibility-action@v1.0.2
        with:
          test-versions: 7.4-
